# Information du site
site_name: "GiL - Mes listes Netflix"
site_description: "Mes listes de Séries et de Films sur Netflix"
site_author: "Gilles LANTERI"
site_url: "https://gilfr.github.io/nxliste/"

# Copyright
copyright: "Copyright &copy; 2020-2023 Gilles Lantéri"

# Configuration
theme:
  name: "material"
  palette:
    - scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Mode sombre
    - scheme: slate
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Mode clair
  favicon: "images/favicon/movie-open-check.svg"
  icon:
    logo: material/movie-open-check
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
  language: fr

# Fichiers techniques
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - javascripts/tables.js

# Extensions
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - admonition
  - tables
